trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
- job:
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  
  - script: |
      --resource-group biceptestRG \
      --name deployment \
      --mode complete \
      --template-file './deploy/main.bicep' \
      --parameters './deploy/params.json'
    displayName: 'Run a multi-line script'