jobs:
- job: State_Resources_Job
  pool: devops
  
  steps:
   #create resources for terraform state:
  - task: AzureCLI@2
    displayName: Create State Resources
    inputs:
      azureSubscription: '$(AZURE_CONN)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az config set bicep.use_binary_from_path=False
        az bicep install
        az deployment group create \
        --name nbBiceDeployment \
        --resource-group NbRG \
        --template-file ../bicep/main.bicep \
        --parameters ../bicep/parameters.json