trigger: none
pr: none
parameters:
- name: environment
  displayName: Terraform Environment (only alphanumeric and dashes)
  type: string
  default: dev
- name: location
  displayName: Location
  type: string
  default: eastus
- name: AZ_DEVOPS_CONN
  type: string
  default:  bicepcon
- name: AzServiceConn
  azureServiceConnection: 'bicepcon'

variables:
  TERRAENV: ${{ parameters.environment }}
  LOCATION: ${{ parameters.location }}
  AZURE_CONN: ${{ parameters.AzServiceConn }}

stages:
### TERRAFORM STATE RESOURCES ###
- stage: bicep_job_01_Network_Implementation
  jobs:
    - template: ./pipeline-jobs/bicep-job01.yml