trigger: none
pr: none
parameters:
- name: environment
  displayName: Terraform Environment (only alphanumeric and dashes)
  type: string
    dev
- name: location
  displayName: Location
  type: string
    eastus
- name: AZ_DEVOPS_CONN
  type: string
    bicepcon

variables:
  TERRAENV: ${{ parameters.environment }}
  LOCATION: ${{ parameters.location }}
  AZ_DEVOPS_SVCONNECTION_CLIENTID: ${{ parameters.AZ_DEVOPS_CONN }}

stages:
### TERRAFORM STATE RESOURCES ###
- stage: bicep_job_01_Network_Implementation
  jobs:
    - template: ./pipeline-jobs/bicep-job01.yml