name: Bicep deployment

on: [workflow_dispatch]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: repo
    - uses: azure/login@v1
      with:
        # auth-type: IDENTITY
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        # allow-no-subscriptions: true
        enable-AzPSSession: true
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: NbRG
        template: ./deploy/main.bicep